name: Release

concurrency:
  group: releasing

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Git Tag to Release, e.g v1.0.0
        type: string

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  create-release:
    needs: build
    runs-on: ubuntu-slim

    permissions:
      contents: write

    env:
      PATH_TO_ARTIFACTS: ${{ github.workspace }}/artifacts
      PATH_TO_RELEASE_ASSETS: ${{ github.workspace }}/release-assets

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          path: ${{ env.PATH_TO_ARTIFACTS }}
          merge-multiple: true

      - name: Create release ZIPs
        env:
          ARTIFACT_PATH: ${{ env.PATH_TO_ARTIFACTS }}
          OUTPUT_PATH: ${{ env.PATH_TO_RELEASE_ASSETS }}
        run: |
          set -eux
          mkdir $OUTPUT_PATH
          cd $ARTIFACT_PATH

          for f in *; do
            [ -e "$f" ] || continue
            (cd "$f" && zip -r "$OUTPUT_PATH/${f}.zip" .)
          done
        shell: bash

      - name: Create Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
          ${{ inputs.tag }} \
          ${{ env.PATH_TO_RELEASE_ASSETS }}/* \
          --repo ${{ github.repository }} \
          --target ${{ github.sha }} \
          --title ${{ inputs.tag }} \
          --generate-notes \
          --latest